### ISSUE TITLE
Integrating Office365 for all incoming mails. 

### ISSUE THREAD

**Issue by iGaurav4** [michelderooij/Connect-Office365Services#10]
When any user from the internet is posting mail to our mail server, ( for example, suppose I own contoso.com and I  

am using office.outlook.com to connect to our mailbox). 

When mail has been posted to contoso.com, I want to examine the mail before it reaches to end-user i.e. contoso.com. 

Suppose I have an application called ContosoExaminerApp. Then my mail flow would be something like  

 

Internet ---> ContosoExaminerApp(it can add some additional information or check for malicious mails) -->  contoso.com(mail server/office 365)  

 

 How can we do that?

**Comment by michelderooij** [comment]
For issues regarding Office 365 services, please post your question on Docs Q&A, [https://docs.microsoft.com/answers/products](https://docs.microsoft.com/answers/products?WT.mc_id=M365-MVP-5000284)
