### ISSUE TITLE
Update-Office365Modules failes on parameter -AllowPrerelease

### ISSUE THREAD

**Issue by dmstork** [michelderooij/Connect-Office365Services#11]
v3.01 fails Update-Office365Modules with an error static that parameter AllowPrerelease is not supported with Find-Module. 
Both on a W10 and W11 device. I only tested with response N on "Would you like to check for pre-release modules"?

```
Checking Exchange Online ManagementFind-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At C:\Users\<snip>\Documents\WindowsPowerShell\Connect-Office365Services.ps1:807 char:98
+ ... Name $local:Item[3] -Repository $local:Repo -AllowPrerelease:$global: ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Find-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Find-Module

Local:2.0.5 Online:N/A
```

**Comment by digitalarche** [comment]
Nope it's just your PowerShellGet is it out of date or at least on the first version 1.0.0.1 
To verify insert this on your posh terminal Get-PackageProvider 2.2.5.0
And after if you didn't have the last version update the package with the required paramater and force switch
Restart your powershell and have fun ;)

**Comment by dmstork** [comment]
Ah, yes. That fixed it. Thought that I had updated everything, but I missed this one. Thanks!
