### ISSUE TITLE
Using the script

### ISSUE THREAD

**Issue by Leunam76** [michelderooij/Connect-Office365Services#13]
Hi, Michel..

When running the script, I only see this:

PowerShell 7.4.2
******************************************************************************
Connect-Office365Services v3.20
Environment:AzureCloud, Administrator:False
Architecture:AMD64, PS:7.4.2, PSGet:2.2.5, PackageManagement:1.4.8.1
******************************************************************************
Collecting Module information ..
Found Exchange Online Management module (v3.5.0)
Found SharePoint Online module (v16.0.24810.12000)
Found Microsoft Teams module (v6.2.0)
Found Microsoft.Graph module (v2.19.0)
Loading personal and system profiles took 1644ms.
PS C:\Users\MyUser>

I'm I doing something wrong ?

Thank you.

**Comment by dc911x** [comment]
Hi @Leunam76 

What are you trying to do? The connect script is loaded and ready to use.

Did you read the description?

> .DESCRIPTION
>     The functions are listed below. Note that functions may call eachother, for example to
>     connect to Exchange Online the Office 365 Credentials the user is prompted to enter these credentials.
>     Also, the credentials are persistent in the current session, there is no need to re-enter credentials
>     when connecting to Exchange Online Protection for example. Should different credentials be required,
>     call Get-Office365Credentials or Get-OnPremisesCredentials again. 
> 
>     Helper Functions:
>     =================
>     - Connect-AzureActiveDirectory  Connects to Azure Active Directory
>     - Connect-AzureRMS              Connects to Azure Rights Management
>     - Connect-ExchangeOnline        Connects to Exchange Online (Graph module)
>     - Connect-AIP                   Connects to Azure Information Protection
>     - Connect-PowerApps             Connects to PowerApps
>     - Connect-ComplianceCenter      Connects to Compliance Center
>     - Connect-SharePointOnline      Connects to SharePoint Online
>     - Connect-MSTeams               Connects to Microsoft Teams
>     - Get-Office365Credentials      Gets Office 365 credentials
>     - Connect-ExchangeOnPremises    Connects to Exchange On-Premises
>     - Get-OnPremisesCredentials     Gets On-Premises credentials
>     - Get-ExchangeOnPremisesFQDN    Gets FQDN for Exchange On-Premises
>     - Get-Office365Tenant           Gets Office 365 tenant name
>     - Set-Office365Environment	    Configures Uri's and region to use
>     - Update-Office365Modules       Updates supported Office 365 modules
>     - Report-Office365Modules       Report on known vs online module versions
>     - Clean-Office365Modules        Cleanup old versions of supported modules
> 
>     Functions to connect to other services provided by the module, e.g. Connect-MSGraph or Connect-MSTeams.
> 
>     To register the PowerShell Test Gallery and install modules from there, use:
>     Register-PSRepository -Name PSGalleryInt -SourceLocation https://www.poshtestgallery.com/ -InstallationPolicy Trusted
>     Install-Module -Name MicrosoftTeams -Repository PSGalleryInt -Force -Scope AllUsers
> 
>     To load the helper functions from your PowerShell profile, put Connect-Office365Services.ps1 in the same location
>     as your $profile file, and edit $profile as follows:
>     & (Join-Path $PSScriptRoot "Connect-Office365Services.ps1")

**Comment by michelderooij** [comment]
As indicated by @dc911x , these are helper functions. To use them, dot-source the script so the helper functions become available in your session. Then use one of the commands, eg Report-Office365Modules.

**Comment by Leunam76** [comment]
@michelderooij @dc911x .... thank you, to read I must indeed, have a nice day,
