### ISSUE TITLE
Check for Administrative privileges

### ISSUE THREAD

**Issue by Rimers** [michelderooij/Connect-Office365Services#2]
When checking for administrative privileges use another method for verification.
Backstory: We use AccessDirector to elevate users temporarily and when using it the users is not in the administrators local group but user still have Administrator privileges.
When your script tests for Administrator privileges it looks at the group and therefore the user is denied using some features even though it is elevated to Administrator.

I tested using code below to verify my users privileges and this check returns the correct value.
$local:IsAdmin = $ThisPrincipal.IsInRole("Administrators")
changed to
$local:IsAdmin = $ThisPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

I changed this on lines 221 and 570 and i can now update modules and so on without doing it manually.
I have not tested on other systems where user is actually part of the Administrators group so please test this before merging into live code.

**Comment by michelderooij** [comment]
Makes sense to use localized label. Already changed in update process, not in prompt. Changed.
