### ISSUE TITLE
Find-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.

### ISSUE THREAD

**Issue by molislaegers** [michelderooij/Connect-Office365Services#6]
When running "Update-Office365Modules"i get the question "Would you like to check for pre-release modules? (y/N) :" regardless the answer, I get the response on all my modules: 

```
Checking Azure Active Directory (v2)
Find-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
```

**Comment by a-bode** [comment]
Try to install a new PowerShellGet version

`Install-Module PowershellGet -Force `

**Comment by molislaegers** [comment]
I tried that, but it didn't resolve the problem.

**Comment by molislaegers** [comment]
Thanks!
