### ISSUE TITLE
Have to run Connect-ExchangeOnline twice

### ISSUE THREAD

**Issue by duminduweera** [michelderooij/Connect-Office365Services#8]
I've copied "Connect-Office365Services.ps1" and "Microsoft.PowerShell_profile.ps1" to $ENV:UserProfile\Documents\WindowsPowerShell and installed Exchange Online Management module as well.

I run Connect-ExchangeOnline and enter my username and password in the **legacy login window** and get the below error.
![Screen Shot 2021-02-26 at 2 14 56 pm](https://user-images.githubusercontent.com/5175348/109250380-aca89680-783d-11eb-8d4d-320b61dfccad.png)

But if I run Connect-ExchangeOnline again, it shows me the **modern login window** where I have to enter my credentials again and it works.

Is this how it's supposed to work or am I missing something?

**Comment by michelderooij** [comment]
The actual parameter is ConnectionUri- should be fixed by now with recent ExchangeOnlineManagement module.
