### ISSUE TITLE
Disconnect-ExchangeOnline session management

### ISSUE THREAD

**Issue by mittalr1975** [michelderooij/Connect-Office365Services#9]
Hi

I am curious to find out how can I disconnect a particular exchange online session. I don't want to kill all the sessions. I want to disconnect only from the session that was created by connect-exchangeonline earlier in a powershell script.

any pointers will be very helpful to my project.

thanks
Raj

**Comment by michelderooij** [comment]
With all the modules switching to REST API (EXO) and Graph, there is less and less usage of sessions, and modules load, some with the option of using prefixes for context (eg Connect-ExchangeOnline -Prefix). No PS session = no disconnect. What Disconnect-ExchangeOnline does for REST sessions is unload the corresponding module.
